# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tbone 0.4.1 ruby lib

Gem::Specification.new do |s|
  s.name = "tbone"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Pavel Tatarsky"]
  s.date = "2014-12-12"
  s.description = "Library for mixing together requirejs backbone and twitter bootstrap"
  s.email = "fazzzenda@mail.ru"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/backbone-rails.js.coffee",
    "app/assets/javascripts/backbone_rails_sync.js.coffee",
    "app/assets/javascripts/bootstrap.js.coffee",
    "app/assets/javascripts/collections/paginated.js.coffee",
    "app/assets/javascripts/helpers/alert_queue.js.coffee",
    "app/assets/javascripts/helpers/layout.js.coffee",
    "app/assets/javascripts/models/.gitkeep",
    "app/assets/javascripts/models/token.js.coffee",
    "app/assets/javascripts/tbone.js.coffee",
    "app/assets/javascripts/tbone_backbone_datalink.js.coffee",
    "app/assets/javascripts/templates/.gitkeep",
    "app/assets/javascripts/templates/common/alert_message.hamlc",
    "app/assets/javascripts/templates/common/confirm.hamlc",
    "app/assets/javascripts/templates/common/pager.hamlc",
    "app/assets/javascripts/views/.gitkeep",
    "app/assets/javascripts/views/common/alert_message_view.js.coffee",
    "app/assets/javascripts/views/common/alert_view.js.coffee",
    "app/assets/javascripts/views/common/confirm_view.js.coffee",
    "app/assets/javascripts/views/common/form_part_view.js.coffee",
    "app/assets/javascripts/views/common/form_view.js.coffee",
    "app/assets/javascripts/views/common/pager_view.js.coffee",
    "app/assets/javascripts/views/tokens/show_view.js.coffee",
    "app/controllers/home_controller.rb",
    "app/controllers/tokens_controller.rb",
    "app/helpers/tbone_helper.rb",
    "app/views/home/index.html.haml",
    "app/views/tokens/show.json.rabl",
    "config/routes.rb",
    "lib/generators/tbone/backbone_model/backbone_model_generator.rb",
    "lib/generators/tbone/backbone_model/templates/collection.coffee.erb",
    "lib/generators/tbone/backbone_model/templates/model.coffee.erb",
    "lib/generators/tbone/install/install_generator.rb",
    "lib/generators/tbone/install/templates/application.json.rabl",
    "lib/generators/tbone/install/templates/requirejs.yml",
    "lib/generators/tbone/rabl_views/rabl_views_generator.rb",
    "lib/generators/tbone/rabl_views/templates/index.rabl.erb",
    "lib/generators/tbone/rabl_views/templates/show.rabl.erb",
    "lib/generators/tbone/scaffold/scaffold_generator.rb",
    "lib/generators/tbone/scaffold_backbone_router/scaffold_backbone_router_generator.rb",
    "lib/generators/tbone/scaffold_backbone_router/templates/confirm.hamljs.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/edit_view.coffee.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/form.hamljs.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/index.hamljs.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/index_view.coffee.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/new_view.coffee.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/object.hamljs.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/object_view.coffee.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/router.coffee.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/show.hamljs.erb",
    "lib/generators/tbone/scaffold_backbone_router/templates/show_view.coffee.erb",
    "lib/generators/tbone/scaffold_controller/scaffold_controller_generator.rb",
    "lib/generators/tbone/scaffold_controller/templates/controller.rb.erb",
    "lib/tbone.rb",
    "lib/tbone/engine.rb",
    "tbone.gemspec",
    "test/helper.rb",
    "test/test_tbone.rb"
  ]
  s.homepage = "http://github.com/vintikzzz/tbone"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.2"
  s.summary = "Library for mixing together requirejs backbone and twitter bootstrap"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n-js>, [">= 0"])
      s.add_runtime_dependency(%q<kaminari>, [">= 0"])
      s.add_runtime_dependency(%q<haml-rails>, [">= 0"])
      s.add_runtime_dependency(%q<coffee-filter>, [">= 0"])
      s.add_runtime_dependency(%q<rabl>, [">= 0"])
      s.add_runtime_dependency(%q<jquery-rails>, [">= 0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<rails-backbone>, [">= 0"])
      s.add_runtime_dependency(%q<requirejs-rails>, [">= 0"])
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<i18n-js>, [">= 0"])
      s.add_dependency(%q<kaminari>, [">= 0"])
      s.add_dependency(%q<haml-rails>, [">= 0"])
      s.add_dependency(%q<coffee-filter>, [">= 0"])
      s.add_dependency(%q<rabl>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<rails-backbone>, [">= 0"])
      s.add_dependency(%q<requirejs-rails>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n-js>, [">= 0"])
    s.add_dependency(%q<kaminari>, [">= 0"])
    s.add_dependency(%q<haml-rails>, [">= 0"])
    s.add_dependency(%q<coffee-filter>, [">= 0"])
    s.add_dependency(%q<rabl>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<rails-backbone>, [">= 0"])
    s.add_dependency(%q<requirejs-rails>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

